# Validator Configuration for GaiaChain
# Configure validator node settings and consensus parameters

[validator]
# Validator identity
moniker = "gaia-validator-1"
identity = "validator_keybase_id"
website = "https://validator.gaiaexchanges.com"
details = "Official GaiaExchanges validator node"

# Validator keys
validator_key_file = "priv_validator_key.json"
validator_state_file = "priv_validator_state.json"
node_key_file = "node_key.json"

# Network configuration
p2p_laddr = "tcp://0.0.0.0:26656"
rpc_laddr = "tcp://0.0.0.0:26657"
grpc_laddr = "0.0.0.0:9090"
grpc_web_laddr = "0.0.0.0:9091"

# Consensus configuration
timeout_propose = "3s"
timeout_propose_delta = "500ms"
timeout_prevote = "1s"
timeout_prevote_delta = "500ms"
timeout_precommit = "1s"
timeout_precommit_delta = "500ms"
timeout_commit = "6s"

# Block and transaction limits
max_block_size_bytes = 2097152  # 2MB
max_gas_per_block = 40000000

# Mempool configuration
max_txs_bytes = 1073741824  # 1GB
max_tx_bytes = 1048576      # 1MB

# State sync configuration
enable_state_sync = false
trust_height = 0
trust_hash = ""
trust_period = "168h0m0s"  # 1 week

# Pruning configuration
pruning = "default"  # "default", "nothing", "everything", or custom
pruning_keep_recent = "100"
pruning_keep_every = "0"
pruning_interval = "10"

# Minimum gas prices
minimum_gas_prices = "0.001ugaia"

# Security settings
cors_allowed_origins = []
cors_allowed_methods = ["HEAD", "GET", "POST"]
cors_allowed_headers = ["Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time"]

# API configuration
[api]
enable = true
swagger = true
address = "tcp://0.0.0.0:1317"
max_open_connections = 1000
rpc_read_timeout = 10
rpc_write_timeout = 0
rpc_max_body_bytes = 1000000
enabled_unsafe_cors = false

# gRPC configuration
[grpc]
enable = true
address = "0.0.0.0:9090"

# State sync snapshots
[state_sync]
snapshot_interval = 1000
snapshot_keep_recent = 2

# Telemetry
[telemetry]
prometheus_retention_time = 0
enable_hostname = false
enable_hostname_label = false
enable_service_label = false
prometheus_listen_addr = ":26660"

# Mempool
[mempool]
recheck = true
broadcast = true
wal_dir = ""
size = 5000
max_txs_bytes = 1073741824
cache_size = 10000
keep_invalid_txs_in_cache = false
max_tx_bytes = 1048576
max_batch_bytes = 0

# FastSync
[fastsync]
version = "v0"

# Consensus
[consensus]
wal_file = "data/cs.wal/wal"
create_empty_blocks = true
create_empty_blocks_interval = "0s"
peer_gossip_sleep_duration = "100ms"
peer_query_maj23_sleep_duration = "2s"

# Transactions indexing
[tx_index]
indexer = "kv"
index_keys = "tx.height,tx.hash"
index_all_keys = false

# Instrumentation
[instrumentation]
prometheus = true
prometheus_listen_addr = ":26660"
max_open_connections = 3
namespace = "tendermint"