shared:
  - ".github/**"
  - ".gitignore"
  - "package-lock.json"
  - "**/package-lock.json"
  - "yarn.lock"
  - "**/yarn.lock"
  - "pnpm-lock.yaml"
  - "**/pnpm-lock.yaml"
  - "poetry.lock"
  - "**/poetry.lock"
  - "requirements*.txt"
  - "**/requirements*.txt"
  - "Pipfile.lock"
  - "**/Pipfile.lock"
  - "go.sum"
  - "**/go.sum"
  - "Gemfile.lock"
  - "**/Gemfile.lock"
  - "*.csproj"
  - "**/*.csproj"
  - "*.sln"
  - "**/*.sln"
  - "Dockerfile*"
  - "docker/**"
topics:
  - name: frontend
    globs:
      - "apps/web/**"
      - "web/**"
      - "ui/**"
      - "**/*.tsx"
      - "**/*.ts"
      - "**/*.jsx"
      - "**/*.vue"
      - "**/package.json"
  - name: backend
    globs:
      - "apps/api/**"
      - "server/**"
      - "api/**"
      - "**/*.py"
      - "**/*.go"
      - "**/*.java"
      - "**/*.kt"
      - "**/*.rb"
  - name: infra
    globs:
      - "infra/**"
      - "terraform/**"
      - "k8s/**"
      - "helm/**"
      - ".github/workflows/**"
  - name: docs
    globs:
      - "docs/**"
      - "**/*.md"
      - "**/*.rst"
  - name: data
    globs:
      - "migrations/**"
      - "db/**"
      - "**/*migration*"
      - "**/*.sql"
