# GaiaChain Core Configuration
# Main blockchain network parameters

[network]
chain_id = "gaia-1"
network_name = "GaiaChain Mainnet"
protocol_version = "1.0.0"
min_gas_price = "0.001ugaia"

[consensus]
# Tendermint/CometBFT consensus parameters
block_time = "6s"
max_block_size = "2MB"
max_gas_per_block = "40000000"
validator_set_size = "100"

[staking]
# Staking and delegation parameters
bond_denom = "ugaia"
unbonding_time = "21d"
max_validators = "100"
min_commission_rate = "0.05"

[governance]
# Governance voting parameters
voting_period = "14d"
deposit_period = "7d"
min_deposit = "1000000ugaia"
quorum = "0.4"
threshold = "0.5"
veto_threshold = "0.334"

[vm]
# Virtual machine configuration
evm_enabled = true
wasm_enabled = true
evm_chain_id = "1337"
gas_price_oracle = "gaia_oracle"

[security]
# Security and cryptography settings
quantum_resistant = true
signature_scheme = "dilithium"
hash_function = "shake256"

[api]
# API server configuration
grpc_port = "9090"
rest_port = "1317"
rpc_port = "26657"
enable_cors = true

[p2p]
# Peer-to-peer networking
listen_port = "26656"
max_peers = "50"
persistent_peers = []
seed_nodes = []

[telemetry]
# Monitoring and telemetry
enabled = true
prometheus_port = "26660"
jaeger_endpoint = "http://localhost:14268/api/traces"

[bridges]
# Cross-chain bridge configuration
ethereum_rpc = "https://mainnet.infura.io/v3/YOUR_KEY"
cosmos_hub_rpc = "https://rpc.cosmos.network"
polkadot_rpc = "wss://rpc.polkadot.io"
bridge_relayer_key = "bridge_relayer"

[development]
# Development and testing settings
testnet_mode = false
faucet_enabled = false
debug_logging = false