name: Auto PR and Smart Split
"on":
  push:
    branches:
      - "**"
    tags:
      ignore:
        - "**"
permissions:
  contents: write
  pull-requests: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  BASE_BRANCH: main
  GH_TOKEN: ${{ github.token }}
  GITHUB_REF_NAME: ${{ github.ref_name }}
jobs:
  auto-pr:
    if: startsWith(github.ref, 'refs/heads/') && github.ref_name != 'main'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Ensure base fetched
        run: |
          git config --global user.name "auto-pr-bot"
          git config --global user.email "actions@users.noreply.github.com"
          git fetch origin ${BASE_BRANCH}:${BASE_BRANCH} --prune || git fetch origin ${BASE_BRANCH} || true
          git checkout ${BASE_BRANCH} >/dev/null 2>&1 || true
          git checkout "${GITHUB_REF_NAME}" || git checkout "${GITHUB_SHA}" || true
      - name: Install PyYAML
        run: |
          python3 -m pip install --user --upgrade pip
          python3 -m pip install --user pyyaml
      - name: Setup GitHub CLI
        run: |
          if ! which gh >/dev/null 2>&1; then
            echo "GitHub CLI not found, installing..."
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update && sudo apt install gh -y
          fi
          gh --version
          gh auth status || echo "Auth status check failed, but continuing..."
      - name: Run smart split / create PRs
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: bash scripts/auto-pr/run.sh