name: Branch Protection Reminder

on:
  push:
    branches: [ main ]

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - name: Reminder
        run: |
          echo "Ensure branch protection rules are enabled for 'main':"
          echo "- Require pull request reviews before merging"
          echo "- Require status checks to pass before merging"
          echo "- Require branches to be up to date before merging"
