name: CI

on:
  pull_request:
    branches: [main, deploy]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm cache clean --force
      - run: rm -rf node_modules package-lock.json
      - run: npm install
      - run: npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm cache clean --force
      - run: rm -rf node_modules package-lock.json
      - run: npm install
      - run: npm run build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm cache clean --force
      - run: rm -rf node_modules package-lock.json
      - run: npm install
      - run: npm test
