name: Commit Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, deploy]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v5
