name: Commit Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, deploy]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      # The commitlint step is removed due to GitHub security policy.
