name: Deploy GaiaExchanges

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting (non-blocking)
      run: npm run lint || echo "Linting warnings detected but continuing deployment"
      
    - name: Build application
      run: npm run build
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      id: vercel-deployment
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        vercel-args: '--prod'
        
    - name: Health Check
      run: |
        sleep 30  # Wait for deployment to be ready
        response=$(curl -s -o /dev/null -w "%{http_code}" "${{ steps.vercel-deployment.outputs.preview-url }}/api/health" || echo "000")
        if [ "$response" != "200" ]; then
          echo "Health check failed with response code: $response"
          exit 1
        fi
        echo "Health check passed"
        
    - name: Notify Success
      if: success()
      run: |
        echo "Deployment successful to ${{ steps.vercel-deployment.outputs.preview-url }}"
        
  notify-failure:
    runs-on: ubuntu-latest
    needs: build-test-deploy
    if: failure()
    
    steps:
    - name: Notify Slack on Failure
      if: always()
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        text: 'GaiaExchanges deployment failed! 🚨'
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        
    - name: Notify Discord on Failure
      if: always()
      uses: Ilshidur/action-discord@master
      with:
        args: '🚨 **GaiaExchanges Deployment Failed** 🚨\nWorkflow: ${{ github.workflow }}\nCommit: ${{ github.sha }}\nBranch: ${{ github.ref_name }}\nActor: ${{ github.actor }}'
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        
    - name: Send Email Notification on Failure
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: 'GaiaExchanges Deployment Failed'
        to: ${{ secrets.NOTIFICATION_EMAIL }}
        from: ${{ secrets.EMAIL_USERNAME }}
        body: |
          Deployment failed for GaiaExchanges!
          
          Workflow: ${{ github.workflow }}
          Repository: ${{ github.repository }}
          Commit: ${{ github.sha }}
          Branch: ${{ github.ref_name }}
          Actor: ${{ github.actor }}
          
          Please check the GitHub Actions logs for more details:
          ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}