name: Docs

on:
  push:
    branches: [main, deploy]
  pull_request:
    branches: [main, deploy]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build documentation
        run: |
          if npm run | grep -q "docs"; then
            npm run docs
          else
            echo "No docs script found. Skipping."
          fi
