name: Prettier

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

permissions:
  contents: read

concurrency:
  group: prettier-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - id: nodefile
        run: |
          if [ -f .nvmrc ]; then
            echo "file=.nvmrc" >> $GITHUB_OUTPUT
          fi
      - name: Setup Node from .nvmrc
        if: steps.nodefile.outputs.file
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Setup Node 20 (fallback)
        if: "!steps.nodefile.outputs.file"
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies (best-effort)
        run: npm ci || true
      - name: Prettier check
        run: |
          if npx --yes prettier --version >/dev/null 2>&1; then
            npx --yes prettier --check .
          elif npm run | grep -q "^ *prettier:check"; then
            npm run prettier:check
          else
            echo "Prettier not configured; skipping."
          fi
