name: Prettier Check

on:
  pull_request:
    branches: [ main ]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run Prettier
        run: npx prettier --check .
