name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run release script
        run: |
          if npm run | grep -q "release"; then
            npm run release
          else
            echo "No release script found. Skipping."
          fi
